import Head from "next/head";
import Image from "next/image";

import io from "socket.io-client";
import { useState } from "react";

const socket = io("http://localhost:5050");

export default function Home() {
  const [message, setMessage] = useState("");
  const [list, setList] = useState([]);

  const handleSubmit = () => {
    // send message to server
    socket.emit("send_message", { message: message });
    setMessage("");
  };

  // listen for message from server
  socket.on("received_message", (data) => {
    console.log(data);
    setList([...list, data]);
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-500 mt-20">
        <h2 className="text-center text-4xl mb-10">Chat App</h2>
        <div className="text-center mb-7">
          <input
            type="text"
            placeholder="message..."
            onChange={(e) => {
              setMessage(e.target.value);
            }}
            value={message}
            className="p-3 rounded-md border-none outline-none bg-cyan-800"
          />
          <button
            className="bg-cyan-800 rounded-3xl p-2 outline-dotted ml-4"
            onClick={() => handleSubmit()}
          >
            Submit
          </button>
        </div>
        {list.map((chat) => (
          <div
            className="bg-cyan-500 shadow-lg shadow-cyan-500/50 rounded-md mb-3 box-s px-5 py-3"
            key={chat.message}
          >
            {chat.message}
          </div>
        ))}
      </div>
    </div>
  );
}
